### ISSUE TITLE
Counters do not work

### ISSUE THREAD

**Issue by Popov85** [olab/Open-Labyrinth#98] opened 2015-09-28 13:04 UTC
Hi everyone!
I faced another issue when working with counters.
The problem is that the counter does not count anything!
I created a new counter called 'Attendance' to allot students with scores for each node viewed. I set the starting value to 0 and Counter Function increment +2 for each node and expected it to get set to 20 after 10 viewed nodes. However, in the process, the counter is not augmenting and the value of the counter keeps being equal to 2!? So, the counter simply is not working. The same situation remains when trying to calculate scores of students for correctly answered questions - the counter simply is not augmented! Any ideas why it is happening? Failed to comprehend it at all! My version of OL is 3.3 sq.
Thank you in advance!

**Comment by sergey-rud** [comment] 2015-09-28 14:56
@Popov85 Hi!
Could you please export the case from your OpenLabyrinth website and attach it? I will import the labyrinth on my local installation and check it.

**Comment by topps** [comment] 2015-09-28 16:42
Sergey, I think that this is less likely to be a programming issue than how the Counter is set up.

Popov85, I am happy to take a look at your case, so please post the Exported case or send direct to me at

Info@openlabyrinth.ca or topps@ucalgary.ca

dt

From: Sergey Rud
Reply-To: olab/Open-Labyrinth
Date: Monday, September 28, 2015 at 8:56 AM
To: olab/Open-Labyrinth
Subject: Re: [Open-Labyrinth] Counters do not work (#98)


@Popov85<https://github.com/Popov85> Hi!
Could you please export the case from your OpenLabyrinth website and attach it? I will import the labyrinth on my local installation and check it.

**Comment by topps** [comment] 2015-09-28 16:49
Counters have been stable for a while so it would be surprising to find that this is a code issue… but you never know, we get surprises all the time.

In the past, I have been tripped by seemingly inconsequential things when setting up my Counter allocations. For example, if you return to the root node at any point in your case, your Counters will be reset to their default values.

When assigning a value to a Counter, you must place an operator in front of it. This applies in the Node Editor, the Counter Grid etc. So, for instance, if you just insert the value e.g. 2, there is no error but it also will behave oddly. You must insert either +2, =2 or –2.

There is also more than one way to alter a Counter value and it is not always obvious in which order these things are happening – this can get confusing. For example, you can alter a Counter value with


  1.  Rule ( IF [[QU_ANSWER:2345]]=“Yes” THEN [[CR:1234]]=10 ELSE  [[CR:1234]]=20;
  2.  A Question response
  3.  A Chat response
  4.  Counter Grid assignment
  5.  Link assignment

So these might be fighting with each other. Let’s take a look at your case. dt

From: Popov85
Reply-To: olab/Open-Labyrinth
Date: Monday, September 28, 2015 at 7:04 AM
To: olab/Open-Labyrinth
Subject: [Open-Labyrinth] Counters do not work (#98)


Hi everyone!
I faced another issue when working with counters.
The problem is that the counter does not count anything!
I created a new counter called 'Attendance' to allot students with scores for each node viewed. I set the starting value to 0 and Counter Function increment +2 for each node and expected it to get set to 20 after 10 viewed nodes. However, in the process, the counter is not augmenting and the value of the counter keeps being equal to 2!? So, the counter simply is not working. The same situation remains when trying to calculate scores of students for correctly answered questions - the counter simply is not augmented! Any ideas why it is happening? Failed to comprehend it at all! My version of OL is 3.3 sq.
Thank you in advance!

**Comment by Popov85** [comment] 2015-09-29 07:13
Hi, guys!
Thank you for your prompt reply!
I've sent our case with counters exported in XML to <b>topps</b> and <b>sergey-rud</b>
Unable to attach the .zip file here as it says the web site does not support that file type.

**Comment by Popov85** [comment] 2015-09-29 09:17
Guys, I've created a test case with counters from scratch. To my surprise, it worked out!
Seemingly, the problem is inside that case that prevents counters from working.
Now, we really need to sort this problem out to make that troublesome case with up to 100 nodes work.
I'd be obliged for any help!

**Comment by Popov85** [comment] 2015-09-29 12:38
Investigating this issue further, I noticed that counters stop working after duplicating a case!
It seems that, there are some bugs inside copying procedure...

**Comment by topps** [comment] 2015-09-29 21:53
Good to know. Which process did you use to copy the case? And which version of OLab are you using? For example, I have found the Duplicate case does not necessarily transfer everything… but Export to zip file and then Import from zip file is more likely to work.

I’m curious as to why you were not able to export to zip… we have not seen that since OLab v2.5

dt

From: Popov85
Reply-To: olab/Open-Labyrinth
Date: Tuesday, September 29, 2015 at 6:38 AM
To: olab/Open-Labyrinth
Cc: David Topps
Subject: Re: [Open-Labyrinth] Counters do not work (#98)


Investigating this issue further, I noticed that counters stop working after duplicating a case!
It seems that, there are some bugs inside copying procedure...

**Comment by Popov85** [comment] 2015-10-30 14:15
Thank you for your comment Topps. I'll try copying cases like that.
Another issue about counters came up: when the value of a counter becomes a negative number, it stops to count further, it neither increases nor decreases the current score.
![debugger](https://cloud.githubusercontent.com/assets/14125796/10847692/aa7ee9fc-7f20-11e5-976b-7811fd2f8987.jpg)
The screenshot shows that we added +2 to the previous score of -2 and the result remained the same - 2. While the current score is a positive number, everything works impeccably.
Please, suggest any solutions to overcome this problem? Is that a programming bug or I do something wrong? It must be something that is easy to fix...

**Comment by topps** [comment] 2015-10-30 14:19
Hmm. They used to be functional when negative- will check this out

On Oct 30, 2015, at 08:15, Popov85 <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you for your comment Topps. I'll try copying cases like that.
Another issue about counters came up: when the value of a counter becomes a negative number, it stops to count further, it neither increases nor decreases the current score.
[debugger]<https://cloud.githubusercontent.com/assets/14125796/10847692/aa7ee9fc-7f20-11e5-976b-7811fd2f8987.jpg>
The screenshot shows that we added +2 to the previous score of -2 and the result remained the same - 2. While the current score is a positive number, everything works impeccably.
Please, suggest any solutions to overcome this problem? Is that a programming bug or I do something wrong? It must be something that is easy to fix...

**Comment by Popov85** [comment] 2015-11-02 11:36
Hi, topps!
To clarify the issue, I've double-checked, the counters linked to multiple-choice questions stop functioning when they become negative, whereas those counters that are linked to nodes (node view) continue to count scores regardless the number sign. For example, if the 1st question (with some given options) is answered incorrectly, your score will not change any more! Or wherever your score becomes negative, it stops counting.
I am wondering if it is a contingency or a feature? I mean is it possible that such the behavior of this type of counters is the norm (for example to prevent the death of a virtual patient in case of selecting wrong pathway)?

**Comment by topps** [comment] 2015-11-02 13:25
Thanks for the clarification. And for being so generous as to consider it a possible feature… but no, it’s just a bug. Will forward to the team. dt

From: Popov85
Reply-To: olab/Open-Labyrinth
Date: Monday, November 2, 2015 at 4:36 AM
To: olab/Open-Labyrinth
Cc: David Topps
Subject: Re: [Open-Labyrinth] Counters do not work (#98)


Hi, topps!
To clarify the issue, I've double-checked, the counters linked to multiple-choice questions stop functioning when they become negative, whereas those counters that are linked to nodes (node view) continue to count scores regardless the number sign. For example, if the 1st question (with some given options) is answered incorrectly, your score will not change any more! Or wherever your score becomes negative, it stops counting.
I am wondering if it is a contingency or a feature? I mean is it possible that such the behavior of this type of counters is the norm (for example to prevent the death of a virtual patient in case of selecting wrong pathway)?

**Comment by sergey-rud** [comment] 2015-11-11 09:59
@Popov85 

> if the 1st question (with some given options) is answered incorrectly (-1 for this question), your score will not change any more! Or wherever your score becomes negative, it stops counting.

Fixed in release-candidate branch.

**Comment by Popov85** [comment] 2015-11-16 08:29
Hi, Sergey!
Thank you for your quick reply. Could you please suggest how to fix it on our installation?
Is it possible at all to substitute some code to make it true without waiting for a new release and reinstalling the OpenLabirynth?
If so, could you please provide some instructions and the new file itself.
My email is: andrey.popov85[at]gmail.com
Thanking you in anticipation!

**Comment by topps** [comment] 2015-11-16 14:44
You should be able to fix it by pulling down the release-candidate branch on Github.

Now… beware… I am not good with Git, having messed up such things myself in the past so I would hesitate to suggest the command sequence. But generally when there is a fix made, it is posted immediately to Git.

I guess one of the things that we should do is to make it clearer in the instructions how to do this. We do not issue Releases often enough to make that the correct approach. dt

From: Popov85
Reply-To: olab/Open-Labyrinth
Date: Monday, November 16, 2015 at 1:29 AM
To: olab/Open-Labyrinth
Cc: David Topps
Subject: Re: [Open-Labyrinth] Counters do not work (#98)


Hi, Sergey!
Thank you for your quick reply. Could you please suggest how to fix it on our installation?
Is it possible at all to substitute some code to make it true without waiting for a new release and reinstalling the OpenLabirynth?
If so, could you please provide some instructions and the new file itself.
My email is: andrey.popov85[at]gmail.com
Thanking you in anticipation!

**Comment by Popov85** [comment] 2015-11-18 16:40
Hi, again!
What we did was the following.
1. I found the release-candidate branch as Sergey suggested.
2. I detected the changes made (file labyrinth.php)
3. Downloaded that file and replaced the current file with the new one in our current installation of OpenLabirynth. 	

As a result I've got this error when trying to play any case:
![error](https://cloud.githubusercontent.com/assets/14125796/11247066/369497dc-8e23-11e5-9df2-cedb0463e0bd.jpg)
"	
Whoops! Looks like something got lost in the Labyrinth."

Did I do anything wrong? Please, give some further instructions!
Thank you!

**Comment by topps** [comment] 2015-11-18 17:00
If you press Ctrl-Q when you get such a screen, it will give you much more in the way of diagnostic details. Can you send us those? dt

**Comment by Popov85** [comment] 2015-11-18 17:59
Hi, Topps, surely, here it is:
![error2](https://cloud.githubusercontent.com/assets/14125796/11249329/d6ddb754-8e2e-11e5-9128-d8caaa97c16d.jpg)

**Comment by topps** [comment] 2015-11-18 18:13
Thanks. Does not mean much to me but I am a pretty amateur code. Perhaps Alexander or one of our PHP or Kohana experts knows what is missing here.

**Comment by Popov85** [comment] 2015-11-19 07:23
I seems like my fault, I downloaded the new .php-file with errors.
Now I am going to test the OpenLab with the correct file!
Thank you!

**Closed** 2016-05-17 12:35 UTC
